can list assets in assetDB

diff --git a/frida/c/makefile b/frida/c/makefile
--- a/frida/c/makefile
+++ b/frida/c/makefile
@@ -6,8 +6,16 @@ ifeq ($(wildcard $(NDK_SDK)),)
 $(error NDK_SDK path $(NDK_SDK) does not exist. Please set NDK_SDK to a valid NDK installation path)
 endif
 
-all:
-	$(NDK_SDK)/ndk-build -C jni 
+check_device:
+	@if [ -z "$$(adb devices | grep -v List | grep device)" ]; then \
+		echo "Error: No Android device connected"; \
+		exit 1; \
+	fi
+
+
+all: check_device
+	$(NDK_SDK)/ndk-build -C jni V=1
+	adb push libs/arm64-v8a/libpatchgame.so /data/local/tmp/
 
 clean:
 	$(NDK_SDK)/ndk-build -C jni clean
